# Lighthouse CI Configuration for Driplo Performance Validation
# Aligns with PRODUCTION_REFACTOR_PLAN.md requirements: Mobile LCP < 2.5s, TBT < 200ms, CLS < 0.1

ci:
  collect:
    # Critical pages as per PRODUCTION_REFACTOR_PLAN
    url:
      - "http://localhost:4173/"                           # Homepage
      - "http://localhost:4173/search"                     # Search with filters
      - "http://localhost:4173/search?q=shoes&category=sneakers" # Search results
      - "http://localhost:4173/category/women"             # Category page with filters  
      - "http://localhost:4173/product/1"                  # Product detail page
      - "http://localhost:4173/checkout"                   # Checkout flow

    # Server configuration for SvelteKit preview
    startServerCommand: "cd apps/web && pnpm build && pnpm preview"
    startServerReadyPattern: "Local:.*http://localhost:4173"
    
    # Run multiple times for statistical significance
    numberOfRuns: 5
    
    # Mobile-first testing configuration (per CLAUDE.md)
    settings:
      chromeFlags: "--no-sandbox --headless --disable-dev-shm-usage --disable-background-timer-throttling --disable-renderer-backgrounding"
      
      # Mobile emulation
      emulatedFormFactor: "mobile"
      
      # 3G Fast network simulation for realistic mobile testing
      throttling:
        rttMs: 150
        throughputKbps: 1638.4
        uploadThroughputKbps: 675.84
        cpuSlowdownMultiplier: 4
      
      # Screen emulation - iPhone SE dimensions
      screenEmulation:
        mobile: true
        width: 375
        height: 667
        deviceScaleFactor: 2
        disabled: false
      
      # Only run categories we care about for performance
      onlyCategories: ["performance", "accessibility", "best-practices", "seo"]

  # Performance budgets based on PRODUCTION_REFACTOR_PLAN requirements
  assert:
    assertions:
      # Core requirement: mobile p75 >= 90%
      "categories:performance": ["error", {"minScore": 0.9}]
      "categories:accessibility": ["error", {"minScore": 0.95}]
      "categories:best-practices": ["error", {"minScore": 0.9}]
      "categories:seo": ["error", {"minScore": 0.9}]
      
      # Critical Core Web Vitals (PRODUCTION_REFACTOR_PLAN: LCP < 2.5s, TBT < 200ms, CLS < 0.1)
      "largest-contentful-paint": ["error", {"maxNumericValue": 2500}]
      "first-contentful-paint": ["warn", {"maxNumericValue": 1800}]
      "cumulative-layout-shift": ["error", {"maxNumericValue": 0.1}]
      "total-blocking-time": ["error", {"maxNumericValue": 200}]
      
      # Interactive performance
      "interactive": ["warn", {"maxNumericValue": 4000}]
      "speed-index": ["warn", {"maxNumericValue": 3000}]
      "first-meaningful-paint": ["warn", {"maxNumericValue": 2500}]
      
      # Resource optimization
      "uses-text-compression": "error"
      "uses-responsive-images": "error"
      "efficient-animated-content": "warn"
      "offscreen-images": "warn"
      "render-blocking-resources": "warn"
      "unminified-css": "error"
      "unminified-javascript": "error"
      "unused-css-rules": "warn"
      "unused-javascript": "warn"
      "modern-image-formats": "warn"
      "uses-optimized-images": "warn"
      "uses-webp-images": "warn"
      "uses-rel-preconnect": "warn"
      "uses-rel-preload": "warn"
      
      # Accessibility requirements (AA compliance)
      "color-contrast": "error"
      "image-alt": "error"
      "label": "error"
      "link-name": "error"
      "button-name": "error"
      "document-title": "error"
      "duplicate-id-aria": "error"
      "heading-order": "warn"
      "html-has-lang": "error"
      "html-lang-valid": "error"
      "landmark-one-main": "error"
      "meta-description": "error"
      "meta-viewport": "error"
      "tabindex": "warn"
      
      # SEO for search and category pages
      "canonical": "warn"
      "http-status-code": "error"
      "is-crawlable": "error"
      "robots-txt": "warn"
      "structured-data": "warn"
      "hreflang": "warn"

  # Upload results for CI/CD integration
  upload:
    target: "temporary-public-storage"
    ignoreDuplicateBuildFailure: true