# Lighthouse CI Configuration for Driplo Performance Validation
# Aligns with CLAUDE.md requirements: mobile p75 ≥ 90, LCP ≤ 1.5s

ci:
  collect:
    # Run multiple times for statistical significance
    numberOfRuns: 5
    
    # Chrome configuration for consistent testing
    settings:
      chromeFlags: "--no-sandbox --headless --disable-dev-shm-usage"
      
      # Mobile-first testing (per CLAUDE.md)
      emulatedFormFactor: "mobile"
      
      # Throttling to simulate real-world mobile conditions
      throttling:
        rttMs: 150              # 3G Fast network simulation
        throughputKbps: 1638.4  # ~1.6 Mbps down
        uploadThroughputKbps: 750  # 0.75 Mbps up
        cpuSlowdownMultiplier: 4   # Low-end mobile CPU
      
      # Only run categories we care about
      onlyCategories: ["performance", "accessibility", "best-practices", "seo"]
      
      # Additional settings for filter component testing
      skipAudits:
        - "uses-http2"          # Not applicable for testing
        - "uses-long-cache-ttl" # Handled by deployment
      
      # Custom audits for filter performance
      extraHeaders:
        "User-Agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36"

  # URLs to test (focusing on filter-heavy pages)
  collect:
    url:
      - "http://localhost:5173/"                    # Homepage
      - "http://localhost:5173/search"              # Main search with filters
      - "http://localhost:5173/search?q=shoes"     # Search results
      - "http://localhost:5173/category/sneakers"  # Category page with filters

  # Performance assertions based on CLAUDE.md requirements
  assert:
    assertions:
      # Core requirement: mobile p75 ≥ 90
      "categories:performance": ["error", {"minScore": 0.9}]
      "categories:accessibility": ["error", {"minScore": 0.95}]
      "categories:best-practices": ["error", {"minScore": 0.9}]
      "categories:seo": ["error", {"minScore": 0.95}]
      
      # Critical Core Web Vitals (CLAUDE.md: LCP ≤ 1.5s)
      "metrics:largest-contentful-paint": ["error", {"maxNumericValue": 1500}]
      "metrics:first-contentful-paint": ["error", {"maxNumericValue": 1200}]
      "metrics:cumulative-layout-shift": ["error", {"maxNumericValue": 0.1}]
      "metrics:total-blocking-time": ["error", {"maxNumericValue": 200}]
      
      # Interactive performance
      "metrics:interactive": ["error", {"maxNumericValue": 2500}]
      "metrics:speed-index": ["error", {"maxNumericValue": 2000}]
      
      # Filter-specific performance budgets
      "metrics:max-potential-fid": ["warn", {"maxNumericValue": 100}]
      "metrics:server-response-time": ["warn", {"maxNumericValue": 200}]
      
      # Accessibility requirements (AA compliance)
      "color-contrast": "error"
      "tap-targets": "error"
      "accessible-names": "error"
      "focus-traps": "error"
      
      # Best practices for filter components
      "uses-responsive-images": "warn"
      "efficient-animated-content": "warn"
      "no-document-write": "error"
      
      # SEO for search and category pages
      "meta-description": "warn"
      "document-title": "error"
      "structured-data": "warn"

  # Upload results for CI/CD integration
  upload:
    target: "temporary-public-storage"
    
  # Server configuration for local testing
  server:
    port: 9001
    
  # Budget configuration for filter components
  budgets:
    - path: "/search"
      resourceSizes:
        - resourceType: "script"
          budget: 200  # KB - includes all filter JS
        - resourceType: "stylesheet" 
          budget: 50   # KB - filter component styles
        - resourceType: "image"
          budget: 300  # KB - brand logos, thumbnails
      
      # Timing budgets for filter interactions
      timings:
        - metric: "interactive"
          budget: 2500
        - metric: "first-contentful-paint"
          budget: 1200
    
    - path: "/category/*"
      resourceSizes:
        - resourceType: "script"
          budget: 180  # KB - category-specific filters
        - resourceType: "total"
          budget: 800  # KB - total page weight